### ISSUE TITLE
Foreign key constraint

### ISSUE THREAD

**Issue by vool** [webpatser/laravel-countries#57]
Getting a  ``SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`` error on mysql 
 Should the id for countries not be set as  increments ?

**Comment by webpatser** [comment]
the error you get has nothing to do with the ID being an increment or not. You need to set the foreign key exactly the same as the primary of the counties. I think you need the unsigned?

`$table->integer('id')->unsigned();`

The ID's used are the ID's used by the UN, so we cannot use increments for this. That's why there are gaps, since countries come and go.

**Comment by vool** [comment]
Hey,

Ah I didn't know that about the UN  ID's

makes sense now
