### ISSUE TITLE
 Method Webpatser\Countries\MigrationCommand::handle() does not exist

### ISSUE THREAD

**Issue by GMounir** [webpatser/laravel-countries#70]
When i run **php artisan countries:migration**
i get  **Method Webpatser\Countries\MigrationCommand::handle() does not exist** on the console 
i'm using Laravel _5.5_

**Comment by DanielBoettner** [comment]
When I changed [MigrationCommand.php line 40](https://github.com/webpatser/laravel-countries/blob/50e06eeb4e0473cd2d1471f59dbd4826908a9771/src/commands/MigrationCommand.php#L40) from **fire()** to **handle()** it worked for me again.

After some googling back and forth, this is what I could dig out:

- Commit [970836c](https://github.com/laravel/framework/commit/970836c5368642d975c56aa71f8aecafddcd3fd8)
- Merge [19827](https://github.com/laravel/framework/pull/19827)
- Merge [19839](https://github.com/laravel/framework/pull/19839)

Also [changelog for 5.5](https://github.com/laravel/framework/releases) has 2 spots where it mentions to use **handle()** instead of **fire()**.

- Artisan console
- Queues

Wasn't able to find any information on when fire() became deprecated in this context.

I hope this helps.

**Comment by keepsafesolutions** [comment]
Yes, just got the same.

**Comment by webpatser** [comment]
See #78

**Comment by abr4xas** [comment]
Hi:

```bash
$ php artisan countries:migration

In BoundMethod.php line 135:
                                                                        
  Method Webpatser\Countries\MigrationCommand::handle() does not exist 
```
